dest: generated

vars:
  global_var: "global_data"

bundles:
  - name: openstack-caracal-nonrpe
    vars:
      bundle_var: "bundle_data"
    components:
      - name: openstack-systemd-checks
      - name: landscape-systemd-checks
      - name: rabbitmq
      - name: etcd
      - name: octavia
  - name: spark
    components:
      - name: spark
  - name: hotsos-test
    components:
      - name: hotsos